### PR TITLE
k vector search

### PR DESCRIPTION
**Pull request by Kvieta1990**
1. I merged in all the commits in the `master` branch into the `develop` branch. Now, the `develop` branch is cleanly ahead of the `master`.

    > I only had one merge conflict which happens on the `.gitignore` file, and I kept the changes from both branches.

   > Also, I was using `Visual Studio Code` which does provide a nice interface for working with the codes and git.

2. Mainly, this pull request (PR) is focusing on the k vector search implementation. It has been tested by ORNL staff (mainly Joe Paddison who is a magnetic people) to be working robustly.

3. I also added in some manual test scripts for users to test out the `develop` branch implementation real quick. As a general user, we can use the following commands to test out the latest test implementation real quick,

    ```
    cd whatever_directory
    wget https://raw.githubusercontent.com/AdvancedPhotonSource/GSAS-II/develop/tests/manual_test/G2full_Linux64.sh
    bash G2full_Linux.sh
    ```

4. For the moment, we only provide the capability of k vector search. We do have the following implementation to call `isodistort`. I will keep working on this, together with the implementation for the capability of showing the satellite peak positions corresponding to the selected k vector in the k vector search output table.

5. Apart from the file updates in the `develop` branch, we also need the compiled Cython modules included in the attached zip package, 
[k_vec_cython_bins.zip](https://github.com/AdvancedPhotonSource/GSAS-II/files/15447644/k_vec_cython_bins.zip)

    > For the manual test script mentioned above, I hosted the binary file (in which I included the needed Cython files) on our own server. This is for sure a temporary solution, as it requires myself to bring together the released GSAS-II binaries and the Cython files to make a new tar file and host it on our own server. Once the Cython compiled modules are included in the released binary package, I can adapt the manual test script to the change.

### CODE REVIEW

**Comment by briantoby** [comment]
What is the value of keeping the manual_test contents? If it is worth distributing, probably it should go into the tests directory, but I question if this is really something that will be of general use. I'd suggest that a better place for it would be in a new dir in [buildtools](https://github.com/AdvancedPhotonSource/GSAS-II-buildtools) if this is worth keeping in GitHub. 

A key issue is going to be getting the [k_vec_cython_bins.zip](https://github.com/AdvancedPhotonSource/GSAS-II/files/15447644/k_vec_cython_bins.zip) binaries out to users. They could be included in the binary tar files, though ideally they would be built as part of the process that creates them. For now that is manual, (see https://github.com/AdvancedPhotonSource/GSAS-II-buildtools/blob/main/localbuild/mac_py3.11.sh and other *py311.sh files in that directory. Perhaps I should consider making that build into a GitHub actions process now rather than waiting to redo the Scons process. We should talk more about how the cython files are compiled. 

What happens if the compiled cython files are not present? Something I did not think about before now will be how to trigger GSAS-II to download an update to the binaries. Usually they do not change. 

I will be on travel from Thursday through the following week so I am probably not going to be able to get much done if not in the next few days.

**Comment by Kvieta1990** [comment]
Sure, I can move the manual_test contents to `buildtools`, as it will be useful to keep for manual testing of GSAS-II development version (codes in the `develop` branch).

For the Cython modules building, we can refer to the repo here, [https://github.com/Kvieta1990/gsasii_dev/tree/main/k_vector_search/cython](https://github.com/Kvieta1990/gsasii_dev/tree/main/k_vector_search/cython). The [kvec_general.pyx](https://github.com/Kvieta1990/gsasii_dev/blob/main/k_vector_search/cython/kvec_general.pyx) file is the source file. The [setup.py](https://github.com/Kvieta1990/gsasii_dev/blob/main/k_vector_search/cython/setup.py) file is the setup config file. For the compiling, we would need the `Cython` package to be available, which can be installed via conda, [https://anaconda.org/conda-forge/cython/](https://anaconda.org/conda-forge/cython/). Then the compile is just a single command, `python setup.py build_ext --inplace`

If we can include the compiled Cython modules in the binary release, that will be perfect. I can then change my manual test script to adapt that change and also I will move the manual test script to `buildtool`.

Please feel free to let me know if anything else or a discussion is needed. Thank you!

**Comment by Kvieta1990** [comment]
Just removed the manual tests stuff to a separate location -- as you @briantoby  mentioned, this test script should not be visible to general users anyhow so I just keep them internal to ORNL people for them to manually test out the latest development version.

Please feel free to let me know if any further comments or anything I can help with the binaries packaging to include the Cython modules.

**Review by briantoby — APPROVED** [review]
looks ready to go

**Pull request merged**
